### ISSUE TITLE
'seasoncount=1' for FIFA 18

### ISSUE THREAD

**Issue by otobongetti** [xAranaktu/FIFA-20-Live-Editor#12]
Aranaktu,

This is not an issue, it's not even related to this project.

But please...

The feature/script I feel I've enjoyed most in your cheat table is the 'seasoncount=1'. As it makes career mode infinite or something like that.

I only wish for you to add this feature to FIFA 18 as it is a really good game.

Please consider.

Thanks.

**Comment by xAranaktu** [comment]
Not going to happen.
However, you can use RDBM to change `seasoncount` in `career_users` table. Effect will be the same.

**Comment by otobongetti** [comment]
Alright, thanks.

Otobong Etti
