### ISSUE TITLE
live editor not showing

### ISSUE THREAD

**Issue by MilanKarssing** [xAranaktu/FIFA-20-Live-Editor#13]
Hi,
I watched the tutorial from FIFER to install the cheat engine and the live editor. But everytime when i try  to drag the live editor into the cheat engine, nothing shows up at the adresses. Does somebody know how to fix this or am i just doing something wrong. Maybe the live editor that i have is not compatible with the cheat engine. The live editor is 20.1.3.8 and the cheat engine is 7.1, both the latest version available.

**Comment by xAranaktu** [comment]
Use [Cheat Engine 6.8.1](https://github.com/cheat-engine/cheat-engine/releases/download/v6.8.1/CheatEngine681.exe)

**Comment by MilanKarssing** [comment]
Thank you it work now
