### ISSUE TITLE
Change Board Objective

### ISSUE THREAD

**Issue by kelincipetarung** [xAranaktu/FIFA-20-Live-Editor#14]
Hello. Is there any way to change my board objective? Especially the youth development. Thanks.

**Comment by xAranaktu** [comment]
https://github.com/xAranaktu/FIFA-20-Live-Editor/wiki/Frequently-asked-questions

**Comment by kelincipetarung** [comment]
Oh my I'm sorry for bothering you because I didn't read the FAQ properly. Thanks for answering.
