### ISSUE TITLE
First leg home goals bug

### ISSUE THREAD

**Issue by denisro2010** [xAranaktu/FIFA-20-Live-Editor#3]
Hi, I'd like to report a quite important and annoying bug: when I set all the matches to be at a certain time of day (e.g. 10:00 PM), then the home goals of the first leg on tournaments such as the UCL reset to zero. 

For example, if I play at home and the game ends 3-2, then in the second leg the aggregate will be 0-2. All the goals scored at home get deleted, for me and also for the CPU if it plays at home and scores one or more goals. I was trying all the options and this happens when I mess with the Match Settings -> time of the day. Maybe all the Match Setting options cause the bug, but I only use to change the time of day one.

Regards.

**Comment by xAranaktu** [comment]
Fixed in v20.1.2.7

[Release Schedule](https://docs.google.com/spreadsheets/d/1XWSaUZJw8BEySWkXTpwMT1mY6xkBpoL5r1QwbA3V41c/edit#gid=0)
