### ISSUE TITLE
How to find sats manually on FM 19?

### ISSUE THREAD

**Issue by Jimmy03** [xAranaktu/FIFA-20-Live-Editor#4]
Any tips on how to find player stats with CE?
I'm not using the table, I just want to edit player stats manually with CE somehow

How should I search? (FM19) Career mode

Is it an array of bytes or what?

**Comment by xAranaktu** [comment]
I don't know man. Every game is different. AOB scan may not work. Maybe there are some strings related to player stats. Anyway, you are asking in wrong place.
