### ISSUE TITLE
Jan Tsang

### ISSUE THREAD

**Issue by jantsang121** [xAranaktu/FIFA-20-Live-Editor#6]
For the manager career, I cannot use the headid such as Big T, Peter Jepsen etc.

**Comment by xAranaktu** [comment]
I don't control which heads can be used and which not. If the head model is on the [FIFA 20 IDs list](https://docs.google.com/spreadsheets/d/1-2wnDyG9PPU7Z8bdf1EPYWwXN_H2o6M8NOmwda_Z0oo/edit#gid=2051219731) then it must work. You simply doing something wrong. If your are using one of the lua scripts then yea, it might not work and you will need to assing the head manually [[TUT] How to edit Manager](http://www.soccergaming.com/index.php?threads/tut-how-to-edit-manager.6467707/)

**Comment by jantsang121** [comment]
I just got this error as per attached.

 



 

Best regards,

Tsang Hin Ching, Jan

**Comment by jantsang121** [comment]
Is it typo mistake?

Sent from my iPhone

On 11 Feb 2020, at 19:42, Jan Tsang <tsanghinching@outlook.com> wrote:

﻿
I just got this error as per attached.

<image001.png>

Best regards,
Tsang Hin Ching, Jan

**Comment by xAranaktu** [comment]
What?

**Comment by jantsang121** [comment]
Sorry to disturb again.

[cid:A1B67D9F-6599-4FC9-9386-E9E1B769CCC9-L0-001]

Sent from my iPhone

On 14 Feb 2020, at 16:41, Paweł <notifications@github.com> wrote:

﻿

What?

**Comment by xAranaktu** [comment]
You didn't attached anything man. You need to do it on github, not on your email

**Comment by jantsang121** [comment]
![9CC0D98F-A619-49A1-A7E7-2AD452484FDF](https://user-images.githubusercontent.com/60908667/74516778-f896df00-4f4b-11ea-96d6-882f519e84e3.jpeg)

**Comment by jantsang121** [comment]
Sorry, bro.

**Comment by xAranaktu** [comment]
It doesn't work because there isn't any player with playerid 27002 in default database.

**Comment by jantsang121** [comment]
But I just find it from the FIFA 20 headid sheet.

**Comment by xAranaktu** [comment]
Ye, and you still can use this head model, but the lua script will not do the job for you in this case. You need to assign the head manually... I've send you link to the tutorial already.

**Comment by jantsang121** [comment]
Million thanks.
