### ISSUE TITLE
Gameplay cannot toggle after recent fifa 20 update

### ISSUE THREAD

**Issue by hafeezyui** [xAranaktu/FIFA-20-Live-Editor#7]
[ ERROR ] 03/14/20 18:48:07 - AOB_DisableSubstitutions AOBScanModule error. Try to restart FIFA and Cheat Engine 
I restarted and yet things still the same.

**Comment by xAranaktu** [comment]
After last game update this script is only working with the Live Editor v20.1.3.6 and newer.
